#' Population frequencies over time
#'
#' This function computes the probability of having at least 1 variant  
#' in the gene list of interest (assuming independence) for a range of ClinVar files
#' 
#' @usage freq_over_time(vcf)
#' @param vcf data.frame; clinvaR-processed vcf from import_file_1000g()
#' @examples 
#' freq_over_time(import_file_1000g())
#' @export

freq_over_time <- function(vcf, dates) {
  if (missing(vcf)) 
    stop('Error: freq_over_time() requires a VCF generated by import_file_1000g()')
  if (missing(dates))
    all_dates <- get_date_list()
  freqs <- lapply(all_dates, function(date) {
    print(sprintf("%s [%s/%s]", date, which(date == all_dates), length(all_dates)))
    merged_vcf <- annotate_1000g(clinvar = get_clinvar(date), vcf = vcf) 
    return(1-prod(1-merged_vcf$AF_1000G))
  }) %>% unlist %>% setNames(all_dates)
  class(freqs) <- c("freq_dates", class(freqs))
  plot(freqs)
  return(freqs)
}


#' Number of Submissions Over Time
#'
#' This function computes the number of unique submissions for point mutations
#' (identified by chromosome, position, reference, alternate) in ClinVar
#' 
#' @usage submissions_over_time(genes)
#' @param genes character; list of genes. 
#' @examples 
#' submissions_over_time(get_genes('lmm_hcm.tsv'))
#' @export

submissions_over_time <- function(genes, dates) {
  if (missing(genes)) {
    stop('Error: submissions_over_time() requires a list of genes')
  }
  if (missing(dates))
    all_dates <- get_date_list()
  submissions <- lapply(all_dates, function(date) {
    clinvar <- get_clinvar(date)
    return(sum(clinvar$GENE %in% genes))
  }) %>% unlist %>% setNames(all_dates)
  class(submissions) <- c("submission_dates", class(submissions))
  plot(submissions)
  return(submissions)
}


#' Plot Aggregate Population Frequencies Over Time
#'
#' This function plots the aggregate population frequency generated by freq_over_time(). 
#'    
#' @usage plot(freqs)
#' @param freqs the named frequencies output by freq_over_time(). 
#' @export

plot.freq_dates <- function(freqs) {
  plot(names(freqs), freqs, type = 'o', xlab = "Dates", ylab = "Frequency", main = "Aggregate Population Frequency")
}


#' Plot Submissions Over Time
#'
#' This function plots the aggregate population frequency generated by submissions_over_time(). 
#'    
#' @usage plot(submissions)
#' @param submissions the named frequencies output by submissions_over_time(). 
#' @export

plot.submission_dates <- function(submissions) {
  plot(names(submissions), submissions, type = 'o', xlab = "Dates", ylab = "Submissions", main = "Submissions Over Time")
}
